import type { RelationshipGamesConfig } from "./types";

export const memoryGamesConfig: RelationshipGamesConfig = {
  id: "veronica-kilig-and-co",
  version: 2,
  title: "Our Memory Games",
  intro: "Three little adventures through the moments, places, and words that became us.",
  finalReward: {
    title: "Case solved. Puzzle complete. Lost girl found.",
    message: "Welcome home, Wifey. 💕",
  },
  dateDetective: {
    title: "Date Detective",
    intro: "Case File: How Did We Fall This Fast? Recover the dates, messages, and memories that created Kilig & Co.",
    questions: [
      {
        id: "first-date",
        type: "multiple-choice",
        prompt: "When did the first WhatsApp conversation and movie date happen?",
        options: ["8 July 2026", "9 July 2026", "10 July 2026"],
        answer: "9 July 2026",
        evidence: "Evidence 01",
        explanation: "The first message was sent at 18:45, and the cinema meeting happened that night.",
      },
      {
        id: "our-date",
        type: "multiple-choice",
        prompt: "Which date did Mahal and Princess later choose as ‘our date’?",
        options: ["9 July 2026", "10 July 2026", "13 July 2026"],
        answer: "10 July 2026",
        evidence: "Evidence 02",
        explanation: "It was the Corniche and beach date Princess described as the most special.",
      },
      {
        id: "mahal-kita",
        type: "multiple-choice",
        prompt: "When did the first written mutual ‘Mahal Kita’ exchange happen?",
        options: ["11 July 2026", "13 July 2026", "16 July 2026"],
        answer: "13 July 2026",
        evidence: "Evidence 03",
        explanation: "13 July holds the first documented written mutual ‘Mahal Kita.’",
      },
      {
        id: "girlfriend",
        type: "multiple-choice",
        prompt: "When did Mahal ask Princess to be his girlfriend?",
        options: ["13 July 2026", "16 July 2026", "19 July 2026"],
        answer: "16 July 2026",
        evidence: "Evidence 04",
        explanation: "The girlfriend question arrived on 16 July 2026.",
      },
      {
        id: "move-in",
        type: "multiple-choice",
        prompt: "When did ‘our place’ become real?",
        options: ["22 July 2026", "26 July 2026", "29 July 2026"],
        answer: "29 July 2026",
        evidence: "Evidence 05",
        explanation: "29 July was the day ‘our place’ became real.",
      },
      {
        id: "save-me",
        type: "speaker",
        prompt: "Who said ‘Come save me’ outside the cinema?",
        options: ["Mahal", "Princess", "Both"],
        answer: "Princess",
        explanation: "Princess was going round in circles and asked Mahal to come save her.",
      },
      {
        id: "flowers",
        type: "speaker",
        prompt: "Who said ‘You deserve flowers too’?",
        options: ["Mahal", "Princess", "Both, on different dates"],
        answer: "Both, on different dates",
        explanation: "Mahal’s flowers were discussed on 14 July; Princess returned the gesture on 18 August.",
      },
      {
        id: "love-first",
        type: "mystery",
        prompt: "Who said ‘I love you’ first?",
        options: ["Mahal", "Princess", "This needs an investigation"],
        answer: "This needs an investigation",
        explanation: "Mahal said he whispered it while Princess slept; Princess remembered consciously saying it first the next morning; Mahal sent the first documented written ‘Mahal Kita.’",
      },
      {
        id: "timeline-order",
        type: "ordering",
        prompt: "Put the first six milestones in their correct order.",
        explanation: "From one movie night to making a home together—the whole case fits.",
        cards: [
          { id: "home", label: "Move-in day", date: "29 July" },
          { id: "movie", label: "First movie date", date: "9 July" },
          { id: "mahal", label: "First written mutual Mahal Kita", date: "13 July" },
          { id: "corniche", label: "Corniche and beach date", date: "10 July" },
          { id: "girlfriend", label: "Girlfriend question", date: "16 July" },
          { id: "engaged", label: "The day we got engaged", date: "22 Aug" },
        ],
        correctOrder: ["movie", "corniche", "mahal", "girlfriend", "home", "engaged"],
      },
    ],
  },
  crossword: {
    title: "Memory Crossword",
    intro: "Every relationship creates its own language. How well do you remember ours?",
    rows: 13,
    cols: 16,
    entries: [
      { id: "hunter", answer: "HUNTERXHUNTER", clue: "The anime connection that made Mahal unusually excited.", memoryHint: "Two hunters and one very excited Mahal.", row: 6, col: 0, direction: "across" },
      { id: "kiligandco", answer: "KILIGANDCO", clue: "The name of the first private app prototype.", memoryHint: "The first APK carried this name.", row: 0, col: 2, direction: "down" },
      { id: "corniche", answer: "CORNICHE", clue: "Where an ordinary walk became the most special date.", memoryHint: "Princess suggested a walk here the morning after the movie.", row: 4, col: 5, direction: "down" },
      { id: "princess", answer: "PRINCESS", clue: "One of the earliest affectionate nicknames.", memoryHint: "Royal treatment was there from the beginning.", row: 5, col: 12, direction: "down" },
      { id: "mangoes", answer: "MANGOES", clue: "The fruit that arrived in three boxes and fed the office.", memoryHint: "Three boxes became an office-wide memory.", row: 4, col: 9, direction: "down" },
      { id: "flowers", answer: "FLOWERS", clue: "A gift both people eventually said the other deserved.", memoryHint: "The same sentence was returned one month later.", row: 2, col: 1, direction: "across" },
      { id: "mahal", answer: "MAHAL", clue: "A word that became part of almost every conversation.", memoryHint: "Love, and the name used most often here.", row: 4, col: 0, direction: "down" },
      { id: "kilig", answer: "KILIG", clue: "The feeling caused by hidden notes, flowers, and sweet messages.", memoryHint: "It is also half the app’s name.", row: 0, col: 2, direction: "across" },
      { id: "beach", answer: "BEACH", clue: "Where dreams were shared and time disappeared.", memoryHint: "A perfect date beside the waves.", row: 11, col: 4, direction: "across" },
      { id: "kneel", answer: "KNEEL", clue: "What does my Princess like me to do?", memoryHint: "Five letters. Your favorite command.", row: 8, col: 11, direction: "across" },
      { id: "vivi", answer: "VIVI", clue: "The nickname that quickly became Princess’s.", memoryHint: "Four letters, twice the same beginning.", row: 8, col: 4, direction: "across" },
    ],
  },
  lostLittleGirl: {
    title: "Find the Lost Little Girl",
    intro: "The night Mahal and Princess finally found each other.",
    rows: 8,
    cols: 12,
    start: { row: 6, col: 0 },
    goal: { row: 1, col: 11 },
    walls: [
      { row: 0, col: 2 }, { row: 0, col: 5 }, { row: 0, col: 8 },
      { row: 1, col: 2 }, { row: 1, col: 5 }, { row: 1, col: 8 },
      { row: 2, col: 2 }, { row: 2, col: 5 }, { row: 2, col: 8 }, { row: 2, col: 10 },
      { row: 3, col: 4 }, { row: 3, col: 5 }, { row: 3, col: 8 }, { row: 3, col: 10 },
      { row: 4, col: 1 }, { row: 4, col: 2 },
      { row: 5, col: 4 }, { row: 5, col: 6 }, { row: 5, col: 7 }, { row: 5, col: 8 }, { row: 5, col: 10 },
      { row: 6, col: 2 }, { row: 6, col: 6 }, { row: 6, col: 10 },
      { row: 7, col: 6 },
    ],
    collectibles: [
      { id: "name-card", position: { row: 6, col: 5 }, title: "Name card", symbol: "P?", memory: "Mahal tried several Princess names before finally learning her name." },
      { id: "movie-ticket", position: { row: 3, col: 7 }, title: "Movie ticket", symbol: "🎟", memory: "The first proper movie date was 9 July 2026." },
      { id: "phone", position: { row: 1, col: 4 }, title: "Phone", symbol: "☎", memory: "Call me—not WhatsApp." },
    ],
  },
};
